server:
  port: 8762

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka-peer2 # add records to /etc/hosts for local testing
    appName: ServiceRegistryCluster
    preferIpAddress: false # use hostname not ip
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/ # two eureka server
      defaultZone: http://eureka-peer1:8761/eureka/, http://eureka-peer3:8763/eureka/ # three eureka server
  server:
      waitTimeInMsWhenSyncEmpty: 0
      enableSelfPreservation: false
