server:
  port: 7070
  
spring:
  application:
    name: test-service
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka/, http://eureka-peer2:8762/eureka/, http://eureka-peer3:8763/eureka/
      